name: Lint and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Linters
        run: |
          isort --check --diff .
          black --check .
          flake8 .

      - name: Run Type Checking (Mypy)
        run: |
          mypy . --ignore-missing-imports

      - name: Run Tests (Pytest)
        run: |
          pytest